Demo/Models/ResistorModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Models
{
    public class ResistorModel
    {
        public List<KeyValuePair<string, List<SelectListItem>>> ResistorDropdownList { get; set; }

        public ResistorModel()
        {
            ResistorDropdownList = new List<KeyValuePair<string, List<SelectListItem>>>();
        }
    }

    public class CalculationModel
    {
        public int Digit { get; set; }
        public int Multiplier { get; set; }
        public double? Tolerance { get; set; }
        public double? Temperature { get; set; }
        public long Ohm { get; set; }
        public double MaxConfidence { get; set; }
        public double MinConfidence { get; set; }

        public static implicit operator CalculationModel(Resistor.Data data)
        {
            CalculationModel model = new CalculationModel();
            model.Digit = data.Digit;
            model.Multiplier = data.Multiplier;
            model.Tolerance = data.Tolerance;
            model.Temperature = data.Temperature;
            model.Ohm = data.Ohm;
            model.MinConfidence = data.Confidence.Min;
            model.MaxConfidence = data.Confidence.Max;
            return model;
        }
    }
}

Demo/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            List<SelectListItem> bandDropdownList = new List<SelectListItem>();
            bandDropdownList.Add(new SelectListItem { Text = "Select Number of Bands", Value = "" });
            bandDropdownList.Add(new SelectListItem{ Text = "3 Bands", Value = "3"});
            bandDropdownList.Add(new SelectListItem{ Text = "4 Bands", Value = "4"});
            bandDropdownList.Add(new SelectListItem{ Text = "5 Bands", Value = "5"});
            bandDropdownList.Add(new SelectListItem{ Text = "6 Bands", Value = "6"});
            ViewBag.BandDropdown = bandDropdownList;
            return View();
        }

        public ActionResult About()
        {
            return View();
        }
    }
}

Demo/Controllers/ResistorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Resistor;
using Demo.Models;

namespace Demo.Controllers
{
    public class ResistorController : Controller
    {
        private readonly Data resistor;

        public ResistorController()
        {
            resistor = new Data();
        }

        //
        // GET: /Resistor/

        public ActionResult Index(int id)
        {
            ResistorType collection = resistor.GetBand(id);
            ResistorModel model = new ResistorModel();

            foreach (var band in collection.Bands)
            {
                string dropdownName = band.GetType().Name;
                List<SelectListItem> list = new List<SelectListItem>();
                list.Add(new SelectListItem { Text = "Select", Value = "" });
                foreach (var code in band.Codes.OrderBy(r => r.Order))
                {
                    list.Add(new SelectListItem {Text = code.Color, Value = code.Order.ToString() });
                }

                model.ResistorDropdownList.Add(new KeyValuePair<string, List<SelectListItem>>(dropdownName, list));
            }

            return View(model);
        }

        public ActionResult Calculate(string value)
        {
            int[] nums = value.Split(',').Select(int.Parse).ToArray();
            resistor.Update(nums.ToList());
            CalculationModel result = resistor;
            return View(result);
        }
    }
}

Demo/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        This is a simple demo of a Resistor Color Code Decrypter.
    </p>
</article>

Demo/Views/Home/Index.cshtml
@using System.Web.Mvc;

@{
    ViewBag.Title = "Main Section";
}

@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
            </p>
        </div>
    </section>
}
 
<div class="row">
    <div id="main">
            @Html.Label("Select Band Count")
            @Html.DropDownList("BandDropdown", ViewBag.BandDropdown as List<SelectListItem>)
            <br />
            <div id="resistor-div">

            </div>
    </div>
</div>

@section scripts{
    <script>
        $("#BandDropdown").change(function () {            
            var selected = $(this).val();

            if (selected != '') {
                var url = '@Url.Action("Index", "Resistor")';
                $("#resistor-div").load(url, { id: selected });
            }
            else {
                $("#resistor-div").empty();
            }

            return false;
        });

        function calculate() {
            var count = $("#count").val();
            var arrayList = new Array(count);
            
            for (var i = 0; i < count; i++) {               

                var id = "#" + i.toString();
                var value = $(id).val();

                if (value != '')
                {
                    arrayList[i] = value;
                }
            }

            if (arrayList.length == count)
            {
                $("#BandDropdown").val("");
                var url = '@Url.Action("Calculate", "Resistor")';
                $("#resistor-div").load(url, { value: arrayList.join(",") });
            }
            else {
                alert("All Bands Must Be Selected Before Calculation Can Begin.");
            }

            return false;
        }

    </script>
}

Demo/Views/Resistor/Calculate.cshtml
@model  Demo.Models.CalculationModel

@{
    Layout = "";
    string calculations = String.Format("{0}Ω ± {1}%", Model.Ohm.ToString("#,##0"), Model.Tolerance*100);

    if(Model.Temperature != null)
    {
        calculations = String.Format("{0} {1}ppm/C°", calculations, Model.Temperature);
    }
    
    ViewBag.Calculations = calculations;
    ViewBag.Confidences = String.Format("{0}Ω - {1}Ω", Model.MinConfidence.ToString("#,##0"), Model.MaxConfidence.ToString("#,##0"));
}

<br />
<div id="results">
    <div style="width: 50%; display: table;">
        <div style="display: table-row">
            <div style="display: table-cell;"> @Html.Label("Digit") </div>
            <div style="display: table-cell;"> @Html.DisplayFor(x => x.Digit)</div>
        </div>
        <div style="display: table-row">
            <div style="display: table-cell;"> @Html.Label("Multiplier") </div>
            <div style="display: table-cell;"> @Html.DisplayFor(x => x.Multiplier)</div>
        </div>
        <div style="display: table-row">
            <div style="display: table-cell;"> @Html.Label("Tolerance") </div>
            <div style="display: table-cell;"> @Html.DisplayFor(x => x.Tolerance)</div>
        </div>

        @if(Model.Temperature != null)
        {
            <div style="display: table-row">
                <div style="display: table-cell;"> @Html.Label("Temperature") </div>
                <div style="display: table-cell;"> @Html.DisplayFor(x => x.Temperature)</div>
            </div>        
        }

        <div style="display: table-row">
            <div style="display: table-cell;"> @Html.Label("Calculations") </div>
            <div style="display: table-cell;"> @ViewBag.Calculations </div>
        </div>

        <div style="display: table-row">
            <div style="display: table-cell;"> @Html.Label("Confidence") </div>
            <div style="display: table-cell;"> @ViewBag.Confidences</div>
        </div>
    </div>
</div>

Demo/Views/Resistor/Index.cshtml
@model  Demo.Models.ResistorModel

@{
    Layout = "";    
}

<br />
<div id="resistor-dropdown-collection">
    @for (int i = 0; i < Model.ResistorDropdownList.Count; i++)
    {
        @Html.Label(Model.ResistorDropdownList[i].Key)
        @Html.DropDownList(i.ToString(), Model.ResistorDropdownList[i].Value as List<SelectListItem>, new {id = i.ToString() })
        <br />
    }
    @Html.Hidden("count", Model.ResistorDropdownList.Count)
    <button id="calculate" type="submit" onclick="calculate()">Calculate</button>
</div>

Demo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        @Html.Partial("_NavBar")
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Demo/Views/Shared/_NavBar.cshtml
<header>
    <div class="content-wrapper">
        <div class="float-left">
            <p class="site-title">@Html.ActionLink("Resistor Color Code Decrypter", "Index", "Home")</p>
        </div>
        <div class="float-right">
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Decrypter", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                </ul>
            </nav>
        </div>
    </div>
</header>